const ACTIONS = {
  MESSAGE: {
    UPDATE: 'MESSAGE_UPDATED',
    CREATE: 'MESSAGE_ADDED',
    DELETE: 'MESSAGE_DELETED',
  },
  USER: {
    CONNECT: 'USER_CONNECTED',
    DISCONNECT: 'USER_DISCONNECTED'
  }
};

const UPDATE_CHAT_TRIGGER = 'CHAT_UPDATED';
const ONLINE_USERS_TRIGGER = 'ONLINE_USERS_UPDATED';

export {ACTIONS, UPDATE_CHAT_TRIGGER, ONLINE_USERS_TRIGGER};
